### ISSUE TITLE
STOP SPAMMING ME

### ISSUE THREAD

**Issue by asmeurer** [conda-forge/repodata-shards#4]
This repo has been sending me multiple notifications per day (over a 200 since yesterday). I never manually subscribed to this repository. 

This is not the first time this has happened, and it's not the first time I've complained about it (https://github.com/conda-forge/releases/issues/1). Frankly, I find this to be completely unacceptable. If you are going to use a repository to do a bunch of actions that will result in hundreds of email spam per day to everyone subscribed, you need to manually remove people from the repository first, or else in some way get their consent before doing so. Given that this is the third time this has happened to me, it shows an utter disregard from the bots team towards the conda-forge community, which is especially egregious given that I've **specifically asked you not to do this in the past**.

CC @conda-forge/core

**Comment by beckermr** [comment]
Please unwatch as we discussed before in the thread above or similar. I cannot unwatch for you.

**Comment by beckermr** [comment]
<img width="1301" alt="Screen Shot 2021-03-23 at 5 26 03 PM" src="https://user-images.githubusercontent.com/5296416/112226976-eb432e00-8bfc-11eb-9ba1-c18baf3bfa78.png">

**Comment by ocefpaf** [comment]
@asmeurer all the automation that goes here is crucial to many pieces in conda-forge and we cannot easily change how it works. Can you please unsubscribe? Not sure how you are getting pulled into this BTW. Didn't you set to unwatch automatically? Let me know if you need any help doing that.

**Comment by ocefpaf** [comment]
PS: we believe that the reason you are getting subscribed is b/c you are a owner of the regro organization, so every repo transferred from there to conda-forge will hold the "watches." There is nothing we can do on our side, only you can unsubscribe. You can also check your setting on regro to avoid something like that happening again in the future.

**Comment by beckermr** [comment]
BTW, I forgot to say sorry again above. I am truly sorry for spamming you again. That was not my intent. I do try very hard to avoid bot spam when working on automation. Clearly, I am not perfect and can do better! Thank you for your understanding.

**Comment by asmeurer** [comment]
I had already removed myself from the regro organization after the last incident, so I'm surprised if that's the source of me being subscribed to this repo. I thought I had also unwatched everything, but maybe not.

I obviously know that I can unwatch the repository. That misses the point though, which is that I shouldn't have to unwatch or unsubscribe from a repository *after* I get 100 notification emails. The spam shouldn't happen in the first place. Please take more care about these things in the future, for example, by creating new repositories that explicitly don't include people, or by checking who is watching/a member of the repo first and notifying them.

**Comment by beckermr** [comment]
I am closing this issue as it appears this is resolved. Thanks everyone!
